conn IPSEC1
     authby=secret
     pfs=yes
     auto=start 
     keyingtries=3
     dpddelay=30
     dpdtimeout=120
     dpdaction=clear
     keyexchange=ike
     phase2=esp
     encapsulation=yes
     vti-interface=vti01
     vti-routing=yes
     rekey=yes
     ike=aes256-sha1;modp1024
     ikelifetime=28800s
     keylife=1h
     type=tunnel
     mark=10/0xffffffff      
     left=10.10.1.10
     leftid=A.A.A.A
     leftsubnet=10.10.1.0/24
     right=X.X.X.X
     rightsubnet=10.10.2.0/24
     rightid=X.X.X.X
conn IPSEC2
     authby=secret
     pfs=yes
     auto=start 
     keyingtries=3
     dpddelay=30
     dpdtimeout=120
     dpdaction=clear
     keyexchange=ike
     phase2=esp
     encapsulation=yes
     vti-interface=vti02
     vti-routing=yes
     rekey=yes
     ike=aes256-sha1;modp1024
     ikelifetime=28800s
     keylife=1h
     type=tunnel
     mark=20/0xffffffff
     left=10.10.1.10
     leftid=A.A.A.A
     leftsubnet=10.10.1.0/24
     right=Y.Y.Y.Y
     rightsubnet=10.10.2.0/24
     rightid=Y.Y.Y.Y
